from fastapi import APIRouter, HTTPException
from .services.agent import chat_with_agent
from typing import Dict

router = APIRouter()

@router.post("/agent")
def converse_with_agent(user_query: str, session_id: str)-> Dict[str, str]:
    """
    Endpoint to handle user-agent conversation.

    Args:
        Contains user query and session ID.

    Returns:
        dict: Response generated by the conversational agent.
    """
    try:
        response = chat_with_agent(user_query, session_id)
        return {"response": response}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error processing query: {e}")

   


